### ISSUE TITLE
Support for Text Command Delay

### ISSUE THREAD

**Issue by OrangeUtan** [KazWolfe/XIVDeck#50]
I'm using "Text Command" in combination with the built-in "Multi Action" to create crafting macros that are longer than 15 steps and have delays in milliseconds (using "Multi Action: Delay").
I was wondering if it would be possible to add an option to "Text Command" to specify a delay. This would be a huge QoL improvement, because these macros get quite long with every "Text Command" beeing followed by a "Multi Action: Delay".

Judging by the EAQ issue, I would understand if this feature could be against the spirit of this Plugin, but I thought I might ask anyways.

**Comment by KazWolfe** [comment]
Hi and thanks for the feature request!

Unfortunately, you've correctly identified that this is something I'm not particularly comfortable supporting as it does go against the intent of the plugin (as well as Dalamud's official plugin guidelines). Multi-action support was intended to allow for people to create actions spanning multiple plugins (e.g. an AFK macro that sent `/afk` to the game and muted your Discord mic), which is why it was left on in the first place.

I *do* have plans to expand the `Text Command` system to support macros (executed via the game's built-in macro system - so subject to the game's own macro limitations), but this likely won't materialize until a major plugin rewrite planned for/around Dawntrail.
