### ISSUE TITLE
No action dropdown?

### ISSUE THREAD

**Issue by Jodanzuki** [KazWolfe/XIVDeck#9]
I have seem some past issues and I can't seem to understand what I am doing wrong. There are no actions in the config. My best guess is that it is failing to connect to the plugin, since no version shows up on the Stream Deck software. Possibly because the listening IP for the plugin is 127.0.0.1?

![image](https://user-images.githubusercontent.com/16529664/162259281-78ccdc50-9b9b-4408-be7c-fd99737be2aa.png)

**Comment by KazWolfe** [comment]
Hi - it appears as though the Stream Deck Plugin runtime is not initializing properly (note that *Runtime Version* is also currently `???`).  This problem lies wholly within the Stream Deck Plugin's code, and is unrelated to the game.

Please provide the following information:

* Is this a fresh install of XIVDeck?
* Has the action button you're trying to configure had any prior configurations on it?
* Does this problem (specifically runtime version being `???`) exist on any other buttons?
* What version of the Stream Deck app are you running?
* What operating system are you running?

Can you also please try the following troubleshooting steps?

1. Fully close and re-open the Stream Deck software (from your taskbar, right-click the Stream Deck icon and select Quit Stream Deck)
2. Uninstall and reinstall the XIVDeck Stream Deck Plugin by right-clicking on one of XIVDeck's Actions in the Action Pane and choosing uninstall.

If this problem still persists past both of these steps, please perform the following troubleshooting steps:

1. Enable [Debug Mode](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging-your-javascript-plugin) on your Stream Deck.
2. Open the Action settings window in your Stream Deck config app
3. Open [`http://localhost:23654`](http://localhost:23654) in Google Chrome and select the entry for `dev.wolf.xivdeck - PropertyInspector`. Select the **Console** tab.
4. Hit F5, wait about 15 seconds, and then take a screenshot of the resulting text.

**Comment by Jodanzuki** [comment]
Hello! I hadn't noticed the plugin runtime was not initializing properly. After you pointed out the issue, I removed the stream deck and forced a driver reinstall. That seems to have solved the problem. Still, just answering a few questions, because it might be useful:
- It was a fresh install.
- It didn't have any configs.
- The error (runtime being ???) showed up on other buttons from the XIVDeck. Couldn't find it on others.
- I am running 5.2.1.15025.
- Windows 10.

**Comment by KazWolfe** [comment]
Alright, thanks for the report and the info. I'll close this for now, but do let me know if it comes back up.

Thanks!
